insert into book values('abc123','Learn Postman','abc','123','sai kalyan');
insert into book values('def456','Springboot','def','456','sai kalyan');
insert into book values('xyz789','Java cookbook','xyz','789','sai sandra');
insert into book values('asd889','Rest APIS','asd','889','uppala');
insert into book values('aaa111','java','aaa','111','uppala');
insert into book values('bbb222','servlets','bbb','222','durga');
insert into book values('ccc333','jsp','ccc','333','chandi');
insert into book values('ddd444','jdbc','ddd','444','rama');
insert into book values('eee555','postman','eee','555','narayana');
insert into book values('fff666','spring security','fff','666','shiva');
insert into book values('ggg777','graphql','ggg','777','durga');
insert into book values('hhh888','javascript','hhh','888','chandi');
insert into book values('iii999','angular','iii','999','shiva');
insert into book values('667kjh','spring security','kjh','667','narayana');